### ISSUE TITLE
Not possible to purchase trains from multiple phases in the same turn

### ISSUE THREAD

**Issue by luizcosta** [justinkwaugh/18www#2]
I encountered this bug when I had money to buy the last 2-train and to buy the first 4-train, but I don't have the option to buy both. If I buy the 2-train I can't select one of the 4-train and have to end my turn.

**Comment by justinkwaugh** [comment]
Hey Luiz, sorry you had a problem.  Can you go to the report bug tab and
download your game state and email to me?  It's very helpful for me to
investigate.

Justin

**Comment by luizcosta** [comment]
I had a corrupt state in the application because I was messing with local storage before, this is not a bug. Sorry for the inconvenience.

**Comment by justinkwaugh** [comment]
No problem!
